-- Constantes
WIN_WIDTH = 800
WIN_HEIGHT = 600
OFFSET_1ST_TILE_X = 40
OFFSET_1ST_TILE_Y = 40
TILE_WIDTH = 10
TILE_HEIGHT = 10
GAME_SURFACE_X = 600
GAME_SURFACE_Y = 400
NB_TILES_X = GAME_SURFACE_X / TILE_WIDTH
NB_TILES_Y = GAME_SURFACE_Y / TILE_HEIGHT

LOSE = false

NB_APPLE_EAT = 0
SNAKE_LENGHT = 0

CELERITY = 0.15
CELERITY_MAX = 0.06

PLAY = false
CHOICE_MENU_POSITION = "play"

FILE_SCORE = "scores.txt"

score_write_time = true -- necessary to write score once time
